package com.cn.zlp.user.pojo;

import java.io.Serializable;
import java.util.Date;

public class TbUserinfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_userinfo.user_id
     *
     * @mbg.generated Sun May 08 13:44:51 CST 2022
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_userinfo.user_name
     *
     * @mbg.generated Sun May 08 13:44:51 CST 2022
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_userinfo.password
     *
     * @mbg.generated Sun May 08 13:44:51 CST 2022
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_userinfo.age
     *
     * @mbg.generated Sun May 08 13:44:51 CST 2022
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_userinfo.address
     *
     * @mbg.generated Sun May 08 13:44:51 CST 2022
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_userinfo.moblie_phone
     *
     * @mbg.generated Sun May 08 13:44:51 CST 2022
     */
    private String mobliePhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_userinfo.created_by
     *
     * @mbg.generated Sun May 08 13:44:51 CST 2022
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_userinfo.created_date
     *
     * @mbg.generated Sun May 08 13:44:51 CST 2022
     */
    private Date createdDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_userinfo.update_by
     *
     * @mbg.generated Sun May 08 13:44:51 CST 2022
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_userinfo.update_date
     *
     * @mbg.generated Sun May 08 13:44:51 CST 2022
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_userinfo.user_id
     *
     * @return the value of tb_userinfo.user_id
     *
     * @mbg.generated Sun May 08 13:44:51 CST 2022
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_userinfo.user_id
     *
     * @param userId the value for tb_userinfo.user_id
     *
     * @mbg.generated Sun May 08 13:44:51 CST 2022
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_userinfo.user_name
     *
     * @return the value of tb_userinfo.user_name
     *
     * @mbg.generated Sun May 08 13:44:51 CST 2022
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_userinfo.user_name
     *
     * @param userName the value for tb_userinfo.user_name
     *
     * @mbg.generated Sun May 08 13:44:51 CST 2022
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_userinfo.password
     *
     * @return the value of tb_userinfo.password
     *
     * @mbg.generated Sun May 08 13:44:51 CST 2022
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_userinfo.password
     *
     * @param password the value for tb_userinfo.password
     *
     * @mbg.generated Sun May 08 13:44:51 CST 2022
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_userinfo.age
     *
     * @return the value of tb_userinfo.age
     *
     * @mbg.generated Sun May 08 13:44:51 CST 2022
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_userinfo.age
     *
     * @param age the value for tb_userinfo.age
     *
     * @mbg.generated Sun May 08 13:44:51 CST 2022
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_userinfo.address
     *
     * @return the value of tb_userinfo.address
     *
     * @mbg.generated Sun May 08 13:44:51 CST 2022
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_userinfo.address
     *
     * @param address the value for tb_userinfo.address
     *
     * @mbg.generated Sun May 08 13:44:51 CST 2022
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_userinfo.moblie_phone
     *
     * @return the value of tb_userinfo.moblie_phone
     *
     * @mbg.generated Sun May 08 13:44:51 CST 2022
     */
    public String getMobliePhone() {
        return mobliePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_userinfo.moblie_phone
     *
     * @param mobliePhone the value for tb_userinfo.moblie_phone
     *
     * @mbg.generated Sun May 08 13:44:51 CST 2022
     */
    public void setMobliePhone(String mobliePhone) {
        this.mobliePhone = mobliePhone == null ? null : mobliePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_userinfo.created_by
     *
     * @return the value of tb_userinfo.created_by
     *
     * @mbg.generated Sun May 08 13:44:51 CST 2022
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_userinfo.created_by
     *
     * @param createdBy the value for tb_userinfo.created_by
     *
     * @mbg.generated Sun May 08 13:44:51 CST 2022
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_userinfo.created_date
     *
     * @return the value of tb_userinfo.created_date
     *
     * @mbg.generated Sun May 08 13:44:51 CST 2022
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_userinfo.created_date
     *
     * @param createdDate the value for tb_userinfo.created_date
     *
     * @mbg.generated Sun May 08 13:44:51 CST 2022
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_userinfo.update_by
     *
     * @return the value of tb_userinfo.update_by
     *
     * @mbg.generated Sun May 08 13:44:51 CST 2022
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_userinfo.update_by
     *
     * @param updateBy the value for tb_userinfo.update_by
     *
     * @mbg.generated Sun May 08 13:44:51 CST 2022
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_userinfo.update_date
     *
     * @return the value of tb_userinfo.update_date
     *
     * @mbg.generated Sun May 08 13:44:51 CST 2022
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_userinfo.update_date
     *
     * @param updateDate the value for tb_userinfo.update_date
     *
     * @mbg.generated Sun May 08 13:44:51 CST 2022
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}