package com.cn.zlp.mapper;

import com.cn.zlp.user.pojo.TbUserinfo;
import com.cn.zlp.user.pojo.TbUserinfoExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TbUserinfoMapper2 {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_userinfo
     *
     * @mbg.generated Sun May 08 13:44:51 CST 2022
     */
    long countByExample(TbUserinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_userinfo
     *
     * @mbg.generated Sun May 08 13:44:51 CST 2022
     */
    int deleteByExample(TbUserinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_userinfo
     *
     * @mbg.generated Sun May 08 13:44:51 CST 2022
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_userinfo
     *
     * @mbg.generated Sun May 08 13:44:51 CST 2022
     */
    int insert(TbUserinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_userinfo
     *
     * @mbg.generated Sun May 08 13:44:51 CST 2022
     */
    int insertSelective(TbUserinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_userinfo
     *
     * @mbg.generated Sun May 08 13:44:51 CST 2022
     */
    List<TbUserinfo> selectByExample(TbUserinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_userinfo
     *
     * @mbg.generated Sun May 08 13:44:51 CST 2022
     */
    TbUserinfo selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_userinfo
     *
     * @mbg.generated Sun May 08 13:44:51 CST 2022
     */
    int updateByExampleSelective(@Param("record") TbUserinfo record, @Param("example") TbUserinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_userinfo
     *
     * @mbg.generated Sun May 08 13:44:51 CST 2022
     */
    int updateByExample(@Param("record") TbUserinfo record, @Param("example") TbUserinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_userinfo
     *
     * @mbg.generated Sun May 08 13:44:51 CST 2022
     */
    int updateByPrimaryKeySelective(TbUserinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_userinfo
     *
     * @mbg.generated Sun May 08 13:44:51 CST 2022
     */
    int updateByPrimaryKey(TbUserinfo record);
}